name: Create package
on:
    workflow_dispatch:
        inputs:
            PACKAGE_VERSION:
                description: 'Package Version'
                required: true

permissions:
    contents: read

jobs:
    tag:
        name: New package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Install Composer dependencies
              uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
              with:
                  composer-options: --no-dev --optimize-autoloader

            - name: Setup pnpm
              uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

            - name: Setup Node.js
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version-file: .nvmrc
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build assets
              run: pnpm build

            - name: Exclude files listed in .distignore
              run: |
                  if [ -f .distignore ]; then
                    mkdir filtered
                    rsync -av --exclude-from='.distignore' . ./filtered
                  fi

            - name: Create zip archive
              run: |
                  cd filtered
                  zip -r ../monei-${{ github.event.inputs.PACKAGE_VERSION }}.zip .

            - name: Upload artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: monei-${{ github.event.inputs.PACKAGE_VERSION }}
                  path: monei-${{ github.event.inputs.PACKAGE_VERSION }}.zip
