name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - uses: php-actions/composer@v6

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'MONEI-WooCommerce.zip'
        exclusions: '*.git* /build/*'

    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifacts: 'MONEI-WooCommerce.zip'
        artifactContentType: 'application/zip'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: monei
