name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      uses: ramsey/composer-install@v3
      with:
        composer-options: --no-dev --optimize-autoloader

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
          node-version: '18'

    - name: Install npm dependencies
      run: npm install

    - name: Build assets with wp-scripts
      run: npm run build

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: monei

    - name: Upload Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        omitBodyDuringUpdate: true
        artifacts: ${{ steps.deploy.outputs.zip-path }}
        artifactContentType: 'application/zip'
        token: ${{ secrets.GITHUB_TOKEN }}
